import { z } from 'zod';

export const applicationCreateSchema = z.object({
  company: z.string().trim().min(1),
  role: z.string().trim().min(1),
  applicationUrl: z.string().trim().url().or(z.string().trim().min(1)),
  priority: z.enum(['P0', 'P1', 'P2', 'P3']),
  status: z.enum(['Not Applied', 'Preparing', 'Applied', 'OA', 'Recruiter Screen', 'Technical Interview', 'Final Round', 'Offer', 'Accepted', 'Rejected', 'Withdrawn', 'Closed']).optional(),
  currentStage: z.string().optional(),
  location: z.string().optional(),
  applicationDeadline: z.string().optional().nullable(),
  dateFound: z.string().optional().nullable(),
  notes: z.string().optional(),
});

export const workflowPayloadSchema = z.object({
  action: z.enum(['apply', 'oa', 'interview', 'reject', 'offer', 'description', 'note', 'contact']),
  resumeVersionId: z.string().optional(),
  emailUsed: z.string().optional(),
  coverLetterStatus: z.string().optional(),
  notes: z.string().optional(),
  platform: z.string().optional(),
  nextActionDue: z.string().optional(),
  currentStage: z.string().optional(),
  status: z.string().optional(),
  scheduledStart: z.string().optional(),
  scheduledEnd: z.string().optional(),
  location: z.string().optional(),
  meetingUrl: z.string().optional(),
  recruiter: z.string().optional(),
  interviewer: z.string().optional(),
  compensationSummary: z.string().optional(),
  content: z.string().optional(),
  category: z.string().optional(),
  name: z.string().optional(),
  title: z.string().optional(),
  email: z.string().optional(),
  relationship: z.string().optional(),
  fullText: z.string().optional(),
  minimumQualifications: z.string().optional(),
  preferredQualifications: z.string().optional(),
  keywords: z.string().optional(),
  sourceUrl: z.string().optional(),
});
